project_id = "tyertyevonuwuifztazm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[functions.setup-2fa]
verify_jwt = true

[functions.verify-2fa]
verify_jwt = true

[functions.disable-2fa]
verify_jwt = true

[functions.check-session-security]
verify_jwt = true

[functions.auto-backup]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.schedule-backups]
verify_jwt = true